//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMCSSampleConsoleApp.EMCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1", ConfigurationName="EMCS.OIOLedsageDokumentOpretServicePortType")]
    public interface OIOLedsageDokumentOpretServicePortType {
        
        // CODEGEN: Generating message contract since the operation getOIOLedsageDokumentOpret is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getOIOLedsageDokumentOpret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse getOIOLedsageDokumentOpret(EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getOIOLedsageDokumentOpret", ReplyAction="*")]
        System.Threading.Tasks.Task<EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse> getOIOLedsageDokumentOpretAsync(EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class OIOLedsageDokumentOpret_IType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HovedOplysningerType hovedOplysningerField;
        
        private VirksomhedIdentifikationStrukturType virksomhedIdentifikationStrukturField;
        
        private System.Xml.XmlElement iE815StrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/", Order=0)]
        public HovedOplysningerType HovedOplysninger {
            get {
                return this.hovedOplysningerField;
            }
            set {
                this.hovedOplysningerField = value;
                this.RaisePropertyChanged("HovedOplysninger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VirksomhedIdentifikationStrukturType VirksomhedIdentifikationStruktur {
            get {
                return this.virksomhedIdentifikationStrukturField;
            }
            set {
                this.virksomhedIdentifikationStrukturField = value;
                this.RaisePropertyChanged("VirksomhedIdentifikationStruktur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement IE815Struktur {
            get {
                return this.iE815StrukturField;
            }
            set {
                this.iE815StrukturField = value;
                this.RaisePropertyChanged("IE815Struktur");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class HovedOplysningerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transaktionIdentifikatorField;
        
        private System.DateTime transaktionTidField;
        
        private bool transaktionTidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionIdentifikator {
            get {
                return this.transaktionIdentifikatorField;
            }
            set {
                this.transaktionIdentifikatorField = value;
                this.RaisePropertyChanged("TransaktionIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TransaktionTid {
            get {
                return this.transaktionTidField;
            }
            set {
                this.transaktionTidField = value;
                this.RaisePropertyChanged("TransaktionTid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaktionTidSpecified {
            get {
                return this.transaktionTidFieldSpecified;
            }
            set {
                this.transaktionTidFieldSpecified = value;
                this.RaisePropertyChanged("TransaktionTidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class FejlStrukturType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fejlIdentifikatorField;
        
        private string fejlTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FejlIdentifikator {
            get {
                return this.fejlIdentifikatorField;
            }
            set {
                this.fejlIdentifikatorField = value;
                this.RaisePropertyChanged("FejlIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlTekst {
            get {
                return this.fejlTekstField;
            }
            set {
                this.fejlTekstField = value;
                this.RaisePropertyChanged("FejlTekst");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class AdvisStrukturType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string advisIdentifikatorField;
        
        private string advisTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string AdvisIdentifikator {
            get {
                return this.advisIdentifikatorField;
            }
            set {
                this.advisIdentifikatorField = value;
                this.RaisePropertyChanged("AdvisIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AdvisTekst {
            get {
                return this.advisTekstField;
            }
            set {
                this.advisTekstField = value;
                this.RaisePropertyChanged("AdvisTekst");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class HovedOplysningerSvarType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transaktionIdentifikatorField;
        
        private string serviceIdentifikatorField;
        
        private System.DateTime transaktionTidField;
        
        private bool transaktionTidFieldSpecified;
        
        private object[] svarStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionIdentifikator {
            get {
                return this.transaktionIdentifikatorField;
            }
            set {
                this.transaktionIdentifikatorField = value;
                this.RaisePropertyChanged("TransaktionIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceIdentifikator {
            get {
                return this.serviceIdentifikatorField;
            }
            set {
                this.serviceIdentifikatorField = value;
                this.RaisePropertyChanged("ServiceIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TransaktionTid {
            get {
                return this.transaktionTidField;
            }
            set {
                this.transaktionTidField = value;
                this.RaisePropertyChanged("TransaktionTid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaktionTidSpecified {
            get {
                return this.transaktionTidFieldSpecified;
            }
            set {
                this.transaktionTidFieldSpecified = value;
                this.RaisePropertyChanged("TransaktionTidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdvisStruktur", typeof(AdvisStrukturType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FejlStruktur", typeof(FejlStrukturType), IsNullable=false)]
        public object[] SvarStruktur {
            get {
                return this.svarStrukturField;
            }
            set {
                this.svarStrukturField = value;
                this.RaisePropertyChanged("SvarStruktur");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class OIOLedsageDokumentOpret_OType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HovedOplysningerSvarType hovedOplysningerSvarField;
        
        private OIOLedsageDokumentOpret_OTypeOutput outputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/", Order=0)]
        public HovedOplysningerSvarType HovedOplysningerSvar {
            get {
                return this.hovedOplysningerSvarField;
            }
            set {
                this.hovedOplysningerSvarField = value;
                this.RaisePropertyChanged("HovedOplysningerSvar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OIOLedsageDokumentOpret_OTypeOutput Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
                this.RaisePropertyChanged("Output");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class OIOLedsageDokumentOpret_OTypeOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IE917BeskedTekst", typeof(string), Namespace="urn:oio:skat:emcs:1.0.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LedsageDokument", typeof(OIOLedsageDokumentOpret_OTypeOutputLedsageDokument), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class OIOLedsageDokumentOpret_OTypeOutputLedsageDokument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ledsagedokumentARCIdentifikatorField;
        
        private System.DateTime ledsagedokumentValideretDatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:skat:emcs:1.0.1", Order=0)]
        public string LedsagedokumentARCIdentifikator {
            get {
                return this.ledsagedokumentARCIdentifikatorField;
            }
            set {
                this.ledsagedokumentARCIdentifikatorField = value;
                this.RaisePropertyChanged("LedsagedokumentARCIdentifikator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/emcs/class/ledsagedokument/xml/schemas/20080301/", DataType="date", Order=1)]
        public System.DateTime LedsagedokumentValideretDato {
            get {
                return this.ledsagedokumentValideretDatoField;
            }
            set {
                this.ledsagedokumentValideretDatoField = value;
                this.RaisePropertyChanged("LedsagedokumentValideretDato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class VirksomhedIdentifikationStrukturType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VirksomhedIdentifikationStrukturTypeIndberetter indberetterField;
        
        private string afgiftOperatoerPunktAfgiftIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VirksomhedIdentifikationStrukturTypeIndberetter Indberetter {
            get {
                return this.indberetterField;
            }
            set {
                this.indberetterField = value;
                this.RaisePropertyChanged("Indberetter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:skat:emcs:1.0.1", Order=1)]
        public string AfgiftOperatoerPunktAfgiftIdentifikator {
            get {
                return this.afgiftOperatoerPunktAfgiftIdentifikatorField;
            }
            set {
                this.afgiftOperatoerPunktAfgiftIdentifikatorField = value;
                this.RaisePropertyChanged("AfgiftOperatoerPunktAfgiftIdentifikator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oio:skat:emcs:ws:1.0.1")]
    public partial class VirksomhedIdentifikationStrukturTypeIndberetter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator {
            get {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set {
                this.virksomhedSENummerIdentifikatorField = value;
                this.RaisePropertyChanged("VirksomhedSENummerIdentifikator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOIOLedsageDokumentOpretRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1", Order=0)]
        public EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_IType OIOLedsageDokumentOpret_I;
        
        public getOIOLedsageDokumentOpretRequest() {
        }
        
        public getOIOLedsageDokumentOpretRequest(EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_IType OIOLedsageDokumentOpret_I) {
            this.OIOLedsageDokumentOpret_I = OIOLedsageDokumentOpret_I;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOIOLedsageDokumentOpretResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:oio:skat:emcs:ws:1.0.1", Order=0)]
        public EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_OType OIOLedsageDokumentOpret_O;
        
        public getOIOLedsageDokumentOpretResponse() {
        }
        
        public getOIOLedsageDokumentOpretResponse(EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_OType OIOLedsageDokumentOpret_O) {
            this.OIOLedsageDokumentOpret_O = OIOLedsageDokumentOpret_O;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OIOLedsageDokumentOpretServicePortTypeChannel : EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OIOLedsageDokumentOpretServicePortTypeClient : System.ServiceModel.ClientBase<EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType>, EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType {
        
        public OIOLedsageDokumentOpretServicePortTypeClient() {
        }
        
        public OIOLedsageDokumentOpretServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OIOLedsageDokumentOpretServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OIOLedsageDokumentOpretServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OIOLedsageDokumentOpretServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType.getOIOLedsageDokumentOpret(EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest request) {
            return base.Channel.getOIOLedsageDokumentOpret(request);
        }
        
        public EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_OType getOIOLedsageDokumentOpret(EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_IType OIOLedsageDokumentOpret_I) {
            EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest inValue = new EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest();
            inValue.OIOLedsageDokumentOpret_I = OIOLedsageDokumentOpret_I;
            EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse retVal = ((EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType)(this)).getOIOLedsageDokumentOpret(inValue);
            return retVal.OIOLedsageDokumentOpret_O;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse> EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType.getOIOLedsageDokumentOpretAsync(EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest request) {
            return base.Channel.getOIOLedsageDokumentOpretAsync(request);
        }
        
        public System.Threading.Tasks.Task<EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretResponse> getOIOLedsageDokumentOpretAsync(EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpret_IType OIOLedsageDokumentOpret_I) {
            EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest inValue = new EMCSSampleConsoleApp.EMCS.getOIOLedsageDokumentOpretRequest();
            inValue.OIOLedsageDokumentOpret_I = OIOLedsageDokumentOpret_I;
            return ((EMCSSampleConsoleApp.EMCS.OIOLedsageDokumentOpretServicePortType)(this)).getOIOLedsageDokumentOpretAsync(inValue);
        }
    }
}
